var pavanpro = angular.module('pavanpro', []);

pavanpro.controller('LinksController', function LinksController($scope) {
  $scope.links = [
    "https://www.youtube.com/user/GitHubGuides/playlists",
    "https://github.com/rachitiitr",
    "https://github.com/viraptor/reverse-interview",
    "https://webgems.io/javascript",
    "https://github.com/collections/learn-to-code",
    "https://github.com/explore",
    "https://www.vogella.com/tutorials/Eclipse/article.html",
    "https://dzone.com/articles/effective-eclipse-shortcut-key",
    "https://www.youtube.com/watch?v=X_NZr_-RaLw",
    "http://eloquentjavascript.net/01_values.html",
    "https://www.google.com/maps/views/u/0/explore?gl=us&vm=4&ll=38.704247,-115.827313&bd=-59.788556,-180,82.878195,180&z=2&pv=2",
    "https://www.mysliderule.com/learning-paths/beginners-guide-front-end-programming/learn/#",
    "http://uptodate.frontendrescue.org/",
    "https://www.google.co.in/search?q=time+lines&es_sm=91&tbm=isch&tbo=u&source=univ&sa=X&ei=Z3-CVeaZBIS1mAWghbuoAw&ved=0CB0QsAQ&biw=1280&bih=644#tbm=isch&q=timelines",
    "http://www.fastcompany.com/3034946/hit-the-ground-running/how-to-stop-putting-things-off-and-make-yourself-get-to-work",
    "https://hbr.org/2014/02/how-to-make-yourself-work-when-you-just-dont-want-to",
    "https://www.google.co.in/search?q=how+to+work&oq=how+to+work&aqs=chrome..69i57j69i60.2755j0j1&sourceid=chrome&es_sm=91&ie=UTF-8",
    "https://developers.google.com/maps/documentation/javascript/streetview",
    "http://angular-ui.github.io/angular-google-maps/#",
    "https://github.com/angular-ui/angular-google-maps",
    "http://angular-ui.github.io/ui-slider/demo/demo.html",
    "Join other publishers in India using Question Hub to create richer content online",
    "https://search.google.com/search-console/welcome?",
    "Organizing planning creative etc",
    "https://unmistakablecreative.com/prime/",
    "https://twitter.com/UnmistakableCEO",
    "SimpliLearn",
    "https://lms.simplilearn.com/courses/2985/CompTIA-Linux%2B-Course/syllabus",
    "https://lms.simplilearn.com/courses/2748/AWS-Technical-Essentials/syllabus",
    "https://lms.simplilearn.com/courses/3045/DevOps-Practitioner-Training/syllabus",
    "github.com",
    "https://github.com/rachitiitr/interview-prep",
    "https://github.com/dreikanter/sublime-bookmarks",
    "https://github.com/fcambus/nginx-resources",
    "https://pavan.pro/",
    "New way of doing website for free",
    "http://awaxman11.github.io/blog/2014/07/13/how-to-create-an-angular-app-using-yeoman-and-deploy-it-to-heroku/",
    "https://www.youtube.com/watch?v=0bOJjAUXjhI",
    "https://collegeinfogeek.com/personal-website/",
    "https://github.com/PavanKundagol/pavan.pro",
    "https://pavan.pro/",
    "https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#emphasis",
    "https://github.com/barryclark/jekyll-now",
    "https://github.com/ronv/colorie",
    "https://jekyllrb.com/docs/",
    "https://jekyllrb.com/resources/",
    "https://www.udemy.com/user/holczerbalazs/",
    "https://www.udemy.com/user/purna-chandra-vidya-sagar-uppuluri/",
    "https://www.udemy.com/user/imtiazahmad4/",
    "https://www.udemy.com/course/performance-testing-using-gatling-advanced-level/",
    "https://www.udemy.com/course/performance-testing-using-gatling/",
    "https://www.udemy.com/user/martin-meadows/",
    "https://learn.co/tracks/bootcamp-prep-v2",
    "https://learn-2.galvanize.com/cohorts/888/blocks/215/content_files/welcome.md"
    ];
});
